publisher_forward_position_controller:
  ros__parameters:

    wait_sec_between_publish: 1
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [-0.38, -1.28, 0.0, -0.83,-0.68, 0.0]
    pos2: [0.0, 0.0,0.0, 0.0,0.0, 0.0]
    pos3: [1.11, 0.46,0.0, 0.67,1.06, 0.0]
    pos4: [0.0, 0.0,0.0, 0.0,0.0, 0.0]
