controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:              # delete entry if controller is not applicable
      type: forward_command_controller/ForwardCommandController

forward_position_controller:                  # delete entry if controller is not applicable
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    interface_name: position

forward_velocity_controller:                  # delete entry if controller is not applicable
  ros__parameters:
    joints:
      - joint3
      - joint6
    interface_name: velocity